### ISSUE TITLE
build error：ERROR: An error occurred during the fetch of repository 'pip_gpu_cuda12_torch

### ISSUE THREAD

**Issue by FightingMan** [alibaba/rtp-llm#28]
https://github.com/alibaba/rtp-llm/blob/v0.1.6/docs/Build.md#%E6%9E%84%E5%BB%BA
```
cd rtp-llm
pip3 install -r ./open_source/deps/requirements_torch_gpu_cuda12.txt (官方文好像多上了一层目录)
bazel build //maga_transformer:maga_transformer --jobs 100 --verbose_failures --config=cuda12_2
# 修改test.py中的模型路径，运行一个实际的模型
bazel test //example:test --jobs 100
```
执行到bazel build报错
```
 ./bazel-5.2.0-linux-x86_64 build //maga_transformer:maga_transformer --jobs 100 --verbose_failures --config=cuda12_2
Starting local Bazel server and connecting to it...
INFO: Repository pip_gpu_cuda12_torch instantiated at:
  /disk2/rtp-llm/WORKSPACE:16:9: in <toplevel>
  /disk2/rtp-llm/deps/pip.bzl:10:16: in pip_deps
  /root/.cache/bazel/_bazel_root/4f1289df2d0c1b99f3cd8d132d4d32ba/external/rules_python/python/pip.bzl:53:19: in pip_install
Repository rule pip_repository defined at:
  /root/.cache/bazel/_bazel_root/4f1289df2d0c1b99f3cd8d132d4d32ba/external/rules_python/python/pip_install/pip_repository.bzl:67:33: in <toplevel>
INFO: Repository pip_gpu_torch instantiated at:
  /disk2/rtp-llm/WORKSPACE:16:9: in <toplevel>
  /disk2/rtp-llm/deps/pip.bzl:4:16: in pip_deps
  /root/.cache/bazel/_bazel_root/4f1289df2d0c1b99f3cd8d132d4d32ba/external/rules_python/python/pip.bzl:53:19: in pip_install
Repository rule pip_repository defined at:
  /root/.cache/bazel/_bazel_root/4f1289df2d0c1b99f3cd8d132d4d32ba/external/rules_python/python/pip_install/pip_repository.bzl:67:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'pip_gpu_cuda12_torch':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/4f1289df2d0c1b99f3cd8d132d4d32ba/external/rules_python/python/pip_install/pip_repository.bzl", line 63, column 13, in _pip_repository_impl
                fail("rules_python_external failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: rules_python_external failed:  (src/main/tools/process-wrapper-legacy.cc:80: "execvp(/opt/conda310/bin/python3, ...)": No such file or directory
)
ERROR: /disk2/rtp-llm/WORKSPACE:16:9: fetching pip_repository rule //external:pip_gpu_cuda12_torch: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/4f1289df2d0c1b99f3cd8d132d4d32ba/external/rules_python/python/pip_install/pip_repository.bzl", line 63, column 13, in _pip_repository_impl
                fail("rules_python_external failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: rules_python_external failed:  (src/main/tools/process-wrapper-legacy.cc:80: "execvp(/opt/conda310/bin/python3, ...)": No such file or directory
)
ERROR: Skipping '//maga_transformer:maga_transformer': no such package '@pip_gpu_cuda12_torch//': rules_python_external failed:  (src/main/tools/process-wrapper-legacy.cc:80: "execvp(/opt/conda310/bin/python3, ...)": No such file or directory
)
WARNING: Target pattern parsing failed.
ERROR: no such package '@pip_gpu_cuda12_torch//': rules_python_external failed:  (src/main/tools/process-wrapper-legacy.cc:80: "execvp(/opt/conda310/bin/python3, ...)": No such file or directory
)
INFO: Elapsed time: 1.724s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: maga_transformer
```

python: 3.10.13
cuda: 12.3
system: centos7
bazel: 5.2.0
gcc: 8.5.0

**Comment by dongjiyingdjy** [comment]
BUILD里指定了python路径：/opt/conda310/bin/python，替换成你本地的python路径即可
另：使用我们提供的镜像可以避免大部分环境问题

**Comment by ZJLi2013** [comment]
while  `.bazelrc` still depends on  `/opt/conda310` , replace to local python in BUILD, doesn't really fix the issue
