### ISSUE TITLE
follow readme then error

### ISSUE THREAD

**Issue by okwinds** [alibaba/rtp-llm#34]
cd rtp-llm

pip3 install -r ./open_source/deps/requirements_torch_gpu.txt
package please check the release page.
pip3 install maga_transformer-0.0.1+cuda118-cp310-cp310-manylinux1_x86_64.whl

TOKENIZER_PATH=/path/to/tokenizer CHECKPOINT_PATH=/path/to/model MODEL_TYPE=your_model_type FT_SERVER_TEST=1 python3 -m maga_transformer.start_server

curl -XPOST http://localhost:8088 -d '{"prompt": "hello, what is your name", "generate_config": {"max_new_tokens": 1000}}'

===========================error   here===========================

[root][03/21/2024 14:54:32][__init__.py:<module>():14][INFO] init logger end
[root][03/21/2024 14:54:32][__init__.py:<module>():30][INFO] failed to load libth_transformer.so with exception: [/rtp-llm/maga_transformer/libs/libth_transformer.so: cannot open shared object file: No such file or directory], try use another path
Traceback (most recent call last):
  File "/rtp-llm/maga_transformer/ops/__init__.py", line 28, in <module>
    torch.classes.load_library(os.path.join(libs_path, "libth_transformer.so")) # type: ignore
  File "/miniconda3/envs/rtpllm/lib/python3.10/site-packages/torch/_classes.py", line 51, in load_library
    torch.ops.load_library(path)
  File "/miniconda3/envs/rtpllm/lib/python3.10/site-packages/torch/_ops.py", line 852, in load_library
    ctypes.CDLL(path)
  File "/miniconda3/envs/rtpllm/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /rtp-llm/maga_transformer/libs/libth_transformer.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda3/envs/rtpllm/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/miniconda3/envs/rtpllm/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/rtp-llm/maga_transformer/__init__.py", line 17, in <module>
    from .ops import *
  File "/rtp-llm/maga_transformer/ops/__init__.py", line 33, in <module>
    so_path = find_th_transformer(bazel_bin_dir)
  File "/rtp-llm/maga_transformer/ops/__init__.py", line 14, in find_th_transformer
    for file in dir_path.iterdir():
  File "/miniconda3/envs/rtpllm/lib/python3.10/pathlib.py", line 1017, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/rtp-llm/maga_transformer/../bazel-bin'

**Comment by ySingularity** [comment]
have a try to 0.0.6 version?

**Comment by ySingularity** [comment]
> FT_SERVER_TEST=1 python3 -m maga_transformer.start_server

This instruction should not be executed in rtp-llm/ , or it will follow relative path package instead of wheel.
Our docs have some errors, and we will update it soon.
