### ISSUE TITLE
2 GPUs with TP=2 run Lora inference, one GPU 

### ISSUE THREAD

**Issue by cwlseu** [alibaba/rtp-llm#43]
1. 2xV100上运行 vicuna-13b + lora， tp=2, 启动后如下所示，这个 gpu1 上 utility = 100% 是正常的吗？
![image](https://github.com/alibaba/rtp-llm/assets/5145788/55505b7b-18dc-4144-913f-f743169f07dc)
2. 我测试过程中，将client程序强行中断，服务中出现如下问题情况：
```
[uvicorn.error][2024-03-28 07:32:57][9079][MainThread][/home/xxxx/.local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py:run_asgi():434][ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/home/xxxx/.local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/xxxx/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/xxxx/.local/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/home/xxxx/.local/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/home/xxxx/.local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/routing.py", line 70, in app
    response = await func(request)
  File "/home/xxxx/.local/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/home/xxxx/.local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/xxxx/.local/lib/python3.10/site-packages/maga_transformer/server/inference_app.py", line 103, in inference
    return await self.inference_server.inference(req, raw_request)
  File "/home/xxxx/.local/lib/python3.10/site-packages/maga_transformer/server/inference_server.py", line 161, in inference
    return await self._infer_wrap(req, raw_request, generate_call)
  File "/home/xxxx/.local/lib/python3.10/site-packages/maga_transformer/server/inference_server.py", line 166, in _infer_wrap
    rep = await self._infer_impl(req, id, raw_request, generate_call)
  File "/home/xxxx/.local/lib/python3.10/site-packages/maga_transformer/server/inference_server.py", line 264, in _infer_impl
    raise asyncio.CancelledError("client disconnects")
asyncio.exceptions.CancelledError: client disconnects
```
这个是有影响的吗？

**Comment by ySingularity** [comment]
1. 是持续这个状态吗 一般来说占用率分别为0%、100%是由于在同步数据，持续卡在这个状态可能是同步失败，如果可以正常输出则是正常现象；
2. 没有 这个是正常通信断开吧

**Comment by jianglan89** [comment]
> 1. 2xV100上运行 vicuna-13b + lora， tp=2, 启动后如下所示，这个 gpu1 上 utility = 100% 是正常的吗？
>    ![image](https://private-user-images.githubusercontent.com/5145788/317660590-55505b7b-18dc-4144-913f-f743169f07dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2Nzc4ODgsIm5iZiI6MTcxMTY3NzU4OCwicGF0aCI6Ii81MTQ1Nzg4LzMxNzY2MDU5MC01NTUwNWI3Yi0xOGRjLTQxNDQtOTEzZi1mNzQzMTY5ZjA3ZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjlUMDE1OTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWY0YmY2MThjOTEwYjlhNjhlMmJiZTFlMzYyMDMzYTczYzRhYjAxMWNlMDMyNDJjNmU2MGIxMDJiYTgyYzE3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.B-cJlb77qGzsHlQ1_tu6Qk1IIvSkTh2uTHBir_PzTUI)
> 2. 我测试过程中，将client程序强行中断，服务中出现如下问题情况：
> 
> ```
> [uvicorn.error][2024-03-28 07:32:57][9079][MainThread][/home/xxxx/.local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py:run_asgi():434][ERROR] Exception in ASGI application
> Traceback (most recent call last):
>   File "/home/xxxx/.local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
>     result = await app(  # type: ignore[func-returns-value]
>   File "/home/xxxx/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
>     return await self.app(scope, receive, send)
>   File "/home/xxxx/.local/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
>     raise exc from None
>   File "/home/xxxx/.local/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
>     await self.app(scope, inner_receive, inner_send)
>   File "/home/xxxx/.local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
>     await super().__call__(scope, receive, send)
>   File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/applications.py", line 116, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
>     await self.app(scope, receive, _send)
>   File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
>     await self.app(scope, receive, send)
>   File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
>     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
>   File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
>     await app(scope, receive, sender)
>   File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/routing.py", line 746, in __call__
>     await route.handle(scope, receive, send)
>   File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
>     await self.app(scope, receive, send)
>   File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
>     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
>   File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
>     await app(scope, receive, sender)
>   File "/home/xxxx/.local/lib/python3.10/site-packages/starlette/routing.py", line 70, in app
>     response = await func(request)
>   File "/home/xxxx/.local/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
>     raw_response = await run_endpoint_function(
>   File "/home/xxxx/.local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
>     return await dependant.call(**values)
>   File "/home/xxxx/.local/lib/python3.10/site-packages/maga_transformer/server/inference_app.py", line 103, in inference
>     return await self.inference_server.inference(req, raw_request)
>   File "/home/xxxx/.local/lib/python3.10/site-packages/maga_transformer/server/inference_server.py", line 161, in inference
>     return await self._infer_wrap(req, raw_request, generate_call)
>   File "/home/xxxx/.local/lib/python3.10/site-packages/maga_transformer/server/inference_server.py", line 166, in _infer_wrap
>     rep = await self._infer_impl(req, id, raw_request, generate_call)
>   File "/home/xxxx/.local/lib/python3.10/site-packages/maga_transformer/server/inference_server.py", line 264, in _infer_impl
>     raise asyncio.CancelledError("client disconnects")
> asyncio.exceptions.CancelledError: client disconnects
> ```
> 
> 这个是有影响的吗？
1. 这也是正常现象，是在等 gpu0 同步数据
2. client 强行断掉之后 _infer_impl raise asyncio.CancelledError("client disconnects") 是属于正常现象
