### ISSUE TITLE
能否开放rpt_llm镜像下载？

### ISSUE THREAD

**Issue by liucw2012** [alibaba/rtp-llm#5]
# python3 ./create_container.py create rtp-llm --gpu
/home/netease/src/rtp-llm/docker/./create_container.py:9: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.spawn
docker pull registry.cn-hangzhou.aliyuncs.com/havenask/rpt_llm:0.0.1
Error response from daemon: pull access denied for registry.cn-hangzhou.aliyuncs.com/havenask/rpt_llm, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Traceback (most recent call last):
  File "/home/netease/src/rtp-llm/docker/./create_container.py", line 510, in <module>
    main()
  File "/home/netease/src/rtp-llm/docker/./create_container.py", line 505, in main
    c.doRun(args)
  File "/home/netease/src/rtp-llm/docker/./create_container.py", line 194, in doRun
    return self.run(args)
  File "/home/netease/src/rtp-llm/docker/./create_container.py", line 281, in run
    self.createOne(args.cname)
  File "/home/netease/src/rtp-llm/docker/./create_container.py", line 208, in createOne
    self.execCMD(DOCKER + ' pull ' + self.getImage())
  File "/home/netease/src/rtp-llm/docker/./create_container.py", line 44, in execCMD
    raise Exception('exec cmd: [%s] failed!' % cmd)
Exception: exec cmd: [docker pull registry.cn-hangzhou.aliyuncs.com/havenask/rpt_llm:0.0.1] failed!
root@netease-virtual-machine:/home/netease/src/rtp-llm/docker# docker pull registry.cn-hangzhou.aliyuncs.com/havenask/rpt_llm:0.0.1
Error response from daemon: pull access denied for registry.cn-hangzhou.aliyuncs.com/havenask/rpt_llm, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by xinfeishi** [comment]
好，我看下这个问题。

**Comment by Quincynickyoung** [comment]
同报错没有权限

**Comment by xinfeishi** [comment]
已经修复。
