### ISSUE TITLE
bazel build 提示：connection timed out: /100.67.130.31 错误

### ISSUE THREAD

**Issue by liucw2012** [alibaba/rtp-llm#6]
执行步骤：
1.  cd rtp-llm
2. pip3 install -r ./maga_transformer/requirements_torch_gpu.txt
3. bazel build //maga_transformer:maga_transformer --jobs 100 --verbose_failures

错误信息：
INFO: Invocation ID: ce4de278-a6e0-44ef-b8ca-4294c34264f5
WARNING: Failed to query remote execution capabilities: connection timed out: /100.67.130.31:8989
io.netty.channel.ConnectTimeoutException: connection timed out: /100.67.130.31:8989
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:613)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
INFO: Repository bazel_skylib instantiated at:
  /home/netease/src/rtp-llm/WORKSPACE:10:10: in <toplevel>
  /home/netease/src/rtp-llm/deps/http.bzl:17:17: in http_deps
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/d927948aed1e393340e80fc39c7fc55c/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>

**Comment by liucw2012** [comment]
删除.bazelrc 中的--remote_cache=grpc://100.67.130.31:8989 相关配置，解决该问题；
