### ISSUE TITLE
新增OPT模型后跑不通，报CUDA错误

### ISSUE THREAD

**Issue by samaritan1998** [alibaba/rtp-llm#95]
新增模型OPT模型（125M），出现
>  CUDABFloat16Type{14,768} ], size: [14, 768]
 ** On entry to GEMM_EX  parameter number 9 had an illegal value
[FT][ERROR][RANK 0][140187678004800][24-07-31 05:18:17] [FT][ERROR] CUDA runtime error: CUBLAS_STATUS_INVALID_VALUE src/fastertransformer/cuda/cublas/cublasMMWrapper.cc:295 
[process-2169938][root][07/31/2024 05:18:17][decoder_engine.py:_generator_loop_wrap():53][INFO] request_id = 1, exception type = <class 'Exception'>, exception str [FT][ERROR] CUDA runtime error: CUBLAS_STATUS_INVALID_VALUE src/fastertransformer/cuda/cublas/cublasMMWrapper.cc:295 
[process-2169938][root][07/31/2024 05:18:17][decoder_engine.py:step():135][ERROR] process run error: [FT][ERROR] CUDA runtime error: CUBLAS_STATUS_INVALID_VALUE src/fastertransformer/cuda/cublas/cublasMMWrapper.cc:295 
, Traceback: Traceback (most recent call last):
  File "/home/maga_transformer/async_decoder_engine/decoder_engine.py", line 123, in step
    self.executor_.process(batch_query)
  File "/home/maga_transformer/async_decoder_engine/normal_model_executor.py", line 58, in process
    all_hidden_states = self._process(batch_query)
  File "/home/maga_transformer/async_decoder_engine/normal_model_executor.py", line 101, in _process
    hidden_states = self.model_ops.gpt_op.forward(
  File "/home/maga_transformer/ops/gpt_ops/gpt_op.py", line 82, in forward
    outputs = self.ft_op.forward(decoder_input,
RuntimeError: [FT][ERROR] CUDA runtime error: CUBLAS_STATUS_INVALID_VALUE src/fastertransformer/cuda/cublas/cublasMMWrapper.cc:295 

环境信息：

驱动：535.161.08

CUDA Version: 12.2

``` python3
from maga_transformer.utils.util import get_config_from_path
from maga_transformer.config.gpt_init_model_parameters import GptInitModelParameters
from maga_transformer.utils.model_weight import W, WeightInfo, \
    ModelWeightInfo, ModelDeployWeightInfo, CkptWeightInfo, identity, transpose
from maga_transformer.models.gpt import GPT
from maga_transformer.utils.model_weight import (W, WeightInfo, ModelWeightInfo, ModelDeployWeightInfo,
                                                 CkptWeightInfo, identity, zeros, transpose, transpose_pad,
                                                 merge_qkv_b, merge_qkv_hf,concat_0)
from maga_transformer.model_factory_register import register_model
from typing import Any, Dict,List, Tuple, Union
from maga_transformer.utils.group_quant_weight_util import get_layer_group_quant_weight_info
import os 
import json 
import functools
import torch


class OptWeightInfo(ModelDeployWeightInfo):
    def _get_weight_info(self):
        return self._get_hf_weight_info()

    def _get_hf_layer_weight_info(self):
        layer_weights = [
            WeightInfo(W.attn_qkv_w, [
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.q_proj.weight', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.k_proj.weight', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.v_proj.weight', identity),
                ], functools.partial(merge_qkv_hf)),
            WeightInfo(W.attn_qkv_b,[
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.q_proj.bias', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.k_proj.bias', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.v_proj.bias', identity),
                ], functools.partial(merge_qkv_b)),


            WeightInfo(W.attn_o_w,[CkptWeightInfo('model.decoder.layers.{i}.self_attn.out_proj.weight', identity)], transpose),
            WeightInfo(W.attn_o_b,[CkptWeightInfo('model.decoder.layers.{i}.self_attn.out_proj.bias', identity)]),

            WeightInfo(W.post_ln_gamma,[CkptWeightInfo('model.decoder.layers.{i}.self_attn_layer_norm.weight', identity)], identity),
            WeightInfo(W.post_ln_beta,[CkptWeightInfo('model.decoder.layers.{i}.self_attn_layer_norm.bias', identity)], identity),

            WeightInfo(W.ffn_w1,[CkptWeightInfo('model.decoder.layers.{i}.fc1.weight', identity)], identity),
            WeightInfo(W.ffn_b1,[CkptWeightInfo('model.decoder.layers.{i}.fc1.bias', identity)], identity),
            WeightInfo(W.ffn_w2,[CkptWeightInfo('model.decoder.layers.{i}.fc2.weight', identity)], identity),
            WeightInfo(W.ffn_b2,[CkptWeightInfo('model.decoder.layers.{i}.fc2.bias', identity)], identity),
            WeightInfo(W.post_ffn_ln_gamma,[CkptWeightInfo('model.decoder.layers.{i}.final_layer_norm.weight', identity)], identity),
            WeightInfo(W.post_ffn_ln_beta,[CkptWeightInfo('model.decoder.layers.{i}.final_layer_norm.bias', identity)], identity),
        ]
        return layer_weights
    
    def _get_hf_weight_info(self):
        weights = [
            WeightInfo(W.embedding, [CkptWeightInfo('model.decoder.embed_tokens.weight', identity)], identity),
            WeightInfo(W.positional_embedding,[CkptWeightInfo('model.decoder.embed_positions.weight', identity)], identity),
            WeightInfo(W.final_ln_gamma,[CkptWeightInfo('model.decoder.final_layer_norm.weight', identity)], identity),
            WeightInfo(W.final_ln_beta,[CkptWeightInfo('model.decoder.final_layer_norm.bias', identity)], identity),
            WeightInfo(W.lm_head,[CkptWeightInfo('lm_head.weight', identity)], identity),
        ]
        return ModelWeightInfo(layer_weights=layer_weights, weights=weights, tp_strategy=self._get_gpt_style_tp_strategy())


class OPT_125M(GPT):
    @staticmethod
    def get_weight_cls():
        return OptWeightInfo

    @classmethod
    def _create_config(cls, ckpt_path: str):
        config_path = os.path.join(ckpt_path, 'config.json')
        with open(config_path) as f:
            config_json = json.load(f)
        config = GptInitModelParameters(
            head_num=0,
            size_per_head=0, 
            layer_num=0, 
            max_seq_len=0, 
            vocab_size=50272,
        )
        config.head_num=config_json['num_attention_heads']
        config.layer_num=config_json.get('num_hidden_layers',config_json.get('n_layers', config.layer_num))
        config.size_per_head=config_json['hidden_size']//config_json['num_attention_heads']
        config.vocab_size=config_json['vocab_size']
        config.special_tokens.bos_token_id=config_json.get('bos_token_id',config.special_tokens.bos_token_id)
        config.special_tokens.eos_token_id=config_json.get('eos_token_id',config.special_tokens.eos_token_id)
        config.hidden_size=config_json['hidden_size']
        return config
        


register_model('OPT_125M', OPT_125M,['facebook/opt-125m'])

```

**Comment by samaritan1998** [comment]
少了一行  layer_weights = self._get_hf_layer_weight_info()

**Comment by samaritan1998** [comment]
from maga_transformer.utils.util import get_config_from_path
from maga_transformer.config.gpt_init_model_parameters import GptInitModelParameters
from maga_transformer.utils.model_weight import W, WeightInfo, \
    ModelWeightInfo, ModelDeployWeightInfo, CkptWeightInfo, identity, transpose
from maga_transformer.models.gpt import GPT
from maga_transformer.utils.model_weight import (W, WeightInfo, ModelWeightInfo, ModelDeployWeightInfo,
                                                 CkptWeightInfo, identity, zeros, transpose, transpose_pad,
                                                 merge_qkv_b, merge_qkv_hf,concat_0)
from maga_transformer.model_factory_register import register_model
from typing import Any, Dict,List, Tuple, Union
from maga_transformer.utils.group_quant_weight_util import get_layer_group_quant_weight_info
import os 
import json 
import functools
import torch

# * https://github.com/huggingface/transformers/blob/main/src/transformers/models/opt/modeling_opt.py#L566

class OptWeightInfo(ModelDeployWeightInfo):
    
    def _get_hf_weight_info(self):
        layer_weights = [
            # * Attention部分 layer_norm部分
            WeightInfo(W.pre_attn_ln_gamma,[CkptWeightInfo('model.decoder.layers.{i}.self_attn_layer_norm.weight', identity)], identity),
            WeightInfo(W.pre_attn_ln_gamma,[CkptWeightInfo('model.decoder.layers.{i}.self_attn_layer_norm.bias', identity)], identity),

            # *  Attention部分
            WeightInfo(W.attn_qkv_w, [
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.q_proj.weight', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.k_proj.weight', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.v_proj.weight', identity),
                ], functools.partial(merge_qkv_hf)),
            WeightInfo(W.attn_qkv_b,[
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.q_proj.bias', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.k_proj.bias', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.v_proj.bias', identity),
                ], functools.partial(merge_qkv_b)),
            
            WeightInfo(W.attn_o_w,[CkptWeightInfo('model.decoder.layers.{i}.self_attn.out_proj.weight', identity)], transpose),
            WeightInfo(W.attn_o_b,[CkptWeightInfo('model.decoder.layers.{i}.self_attn.out_proj.bias', identity)], identity),

            # * Attention后
            WeightInfo(W.post_ln_gamma,[CkptWeightInfo('model.decoder.layers.{i}.final_layer_norm.weight', identity)], identity),
            WeightInfo(W.post_ln_beta,[CkptWeightInfo('model.decoder.layers.{i}.final_layer_norm.bias', identity)], identity),
            
            # * FFN部分 
            WeightInfo(W.ffn_w3,[CkptWeightInfo('model.decoder.layers.{i}.fc1.weight', identity)], transpose),
            WeightInfo(W.ffn_b3,[CkptWeightInfo('model.decoder.layers.{i}.fc1.bias', identity)], identity),
            WeightInfo(W.ffn_w2,[CkptWeightInfo('model.decoder.layers.{i}.fc2.weight', identity)], transpose),
            WeightInfo(W.ffn_b2,[CkptWeightInfo('model.decoder.layers.{i}.fc2.bias', identity)], identity),
        ]
        
        weights = [
            WeightInfo(W.embedding, [CkptWeightInfo('model.decoder.embed_tokens.weight', identity)], identity),
            WeightInfo(W.positional_embedding,[CkptWeightInfo('model.decoder.embed_positions.weight', identity)], identity),
            WeightInfo(W.final_ln_gamma,[CkptWeightInfo('model.decoder.final_layer_norm.weight', identity)], identity),
            WeightInfo(W.final_ln_beta,[CkptWeightInfo('model.decoder.final_layer_norm.bias', identity)], identity),
            WeightInfo(W.lm_head,[CkptWeightInfo('lm_head.weight', identity)], identity),
        ]
        
        return ModelWeightInfo(layer_weights=layer_weights, weights=weights, tp_strategy=self._get_gpt_style_tp_strategy())


class OPT_125M(GPT):
    @staticmethod
    def get_weight_cls():
        return OptWeightInfo

    @classmethod
    def _create_config(cls, ckpt_path: str):
        config_path = os.path.join(ckpt_path, 'config.json')
        with open(config_path) as f:
            config_json = json.load(f)
        config = GptInitModelParameters(
            head_num=0,
            size_per_head=0, 
            layer_num=0, 
            max_seq_len=0, 
            vocab_size=50272,
        )
        config.head_num=config_json['num_attention_heads']
        config.layer_num=config_json.get('num_hidden_layers', 12)
        config.size_per_head=config_json['hidden_size'] // config_json['num_attention_heads']
        config.vocab_size=config_json['vocab_size']
        config.hidden_size=config_json['hidden_size']
        config.max_seq_len = 2048
        return config

register_model('OPT_125M', OPT_125M, ['facebook/opt-125m'])

**Comment by samaritan1998** [comment]
`from maga_transformer.utils.util import get_config_from_path
from maga_transformer.config.gpt_init_model_parameters import GptInitModelParameters
from maga_transformer.utils.model_weight import W, WeightInfo, \
    ModelWeightInfo, ModelDeployWeightInfo, CkptWeightInfo, identity, transpose
from maga_transformer.models.gpt import GPT
from maga_transformer.utils.model_weight import (W, WeightInfo, ModelWeightInfo, ModelDeployWeightInfo,
                                                 CkptWeightInfo, identity, zeros, transpose, transpose_pad,
                                                 merge_qkv_b, merge_qkv_hf,concat_0)
from maga_transformer.model_factory_register import register_model
from typing import Any, Dict,List, Tuple, Union
from maga_transformer.utils.group_quant_weight_util import get_layer_group_quant_weight_info
import os 
import json 
import functools
import torch

# * https://github.com/huggingface/transformers/blob/main/src/transformers/models/opt/modeling_opt.py#L566

class OptWeightInfo(ModelDeployWeightInfo):
    
    def _get_hf_weight_info(self):
        layer_weights = [
            # * Attention部分 layer_norm部分
            WeightInfo(W.pre_attn_ln_gamma,[CkptWeightInfo('model.decoder.layers.{i}.self_attn_layer_norm.weight', identity)], identity),
            WeightInfo(W.pre_attn_ln_gamma,[CkptWeightInfo('model.decoder.layers.{i}.self_attn_layer_norm.bias', identity)], identity),

            # *  Attention部分
            WeightInfo(W.attn_qkv_w, [
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.q_proj.weight', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.k_proj.weight', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.v_proj.weight', identity),
                ], functools.partial(merge_qkv_hf)),
            WeightInfo(W.attn_qkv_b,[
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.q_proj.bias', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.k_proj.bias', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.v_proj.bias', identity),
                ], functools.partial(merge_qkv_b)),
            
            WeightInfo(W.attn_o_w,[CkptWeightInfo('model.decoder.layers.{i}.self_attn.out_proj.weight', identity)], transpose),
            WeightInfo(W.attn_o_b,[CkptWeightInfo('model.decoder.layers.{i}.self_attn.out_proj.bias', identity)], identity),

            # * Attention后
            WeightInfo(W.post_ln_gamma,[CkptWeightInfo('model.decoder.layers.{i}.final_layer_norm.weight', identity)], identity),
            WeightInfo(W.post_ln_beta,[CkptWeightInfo('model.decoder.layers.{i}.final_layer_norm.bias', identity)], identity),
            
            # * FFN部分 
            WeightInfo(W.ffn_w3,[CkptWeightInfo('model.decoder.layers.{i}.fc1.weight', identity)], transpose),
            WeightInfo(W.ffn_b3,[CkptWeightInfo('model.decoder.layers.{i}.fc1.bias', identity)], identity),
            WeightInfo(W.ffn_w2,[CkptWeightInfo('model.decoder.layers.{i}.fc2.weight', identity)], transpose),
            WeightInfo(W.ffn_b2,[CkptWeightInfo('model.decoder.layers.{i}.fc2.bias', identity)], identity),
        ]
        
        weights = [
            WeightInfo(W.embedding, [CkptWeightInfo('model.decoder.embed_tokens.weight', identity)], identity),
            WeightInfo(W.positional_embedding,[CkptWeightInfo('model.decoder.embed_positions.weight', identity)], identity),
            WeightInfo(W.final_ln_gamma,[CkptWeightInfo('model.decoder.final_layer_norm.weight', identity)], identity),
            WeightInfo(W.final_ln_beta,[CkptWeightInfo('model.decoder.final_layer_norm.bias', identity)], identity),
            WeightInfo(W.lm_head,[CkptWeightInfo('lm_head.weight', identity)], identity),
        ]
        
        return ModelWeightInfo(layer_weights=layer_weights, weights=weights, tp_strategy=self._get_gpt_style_tp_strategy())


class OPT_125M(GPT):
    @staticmethod
    def get_weight_cls():
        return OptWeightInfo

    @classmethod
    def _create_config(cls, ckpt_path: str):
        config_path = os.path.join(ckpt_path, 'config.json')
        with open(config_path) as f:
            config_json = json.load(f)
        config = GptInitModelParameters(
            head_num=0,
            size_per_head=0, 
            layer_num=0, 
            max_seq_len=0, 
            vocab_size=50272,
        )
        config.head_num=config_json['num_attention_heads']
        config.layer_num=config_json.get('num_hidden_layers', 12)
        config.size_per_head=config_json['hidden_size'] // config_json['num_attention_heads']
        config.vocab_size=config_json['vocab_size']
        config.hidden_size=config_json['hidden_size']
        config.max_seq_len = 2048
        return config

register_model('OPT_125M', OPT_125M, ['facebook/opt-125m'])`

**Comment by samaritan1998** [comment]
```python
from maga_transformer.utils.util import get_config_from_path
from maga_transformer.config.gpt_init_model_parameters import GptInitModelParameters
from maga_transformer.utils.model_weight import W, WeightInfo, \
    ModelWeightInfo, ModelDeployWeightInfo, CkptWeightInfo, identity, transpose
from maga_transformer.models.gpt import GPT
from maga_transformer.utils.model_weight import (W, WeightInfo, ModelWeightInfo, ModelDeployWeightInfo,
                                                 CkptWeightInfo, identity, zeros, transpose, transpose_pad,
                                                 merge_qkv_b, merge_qkv_hf,concat_0)
from maga_transformer.model_factory_register import register_model
from typing import Any, Dict,List, Tuple, Union
from maga_transformer.utils.group_quant_weight_util import get_layer_group_quant_weight_info
import os 
import json 
import functools
import torch

# * https://github.com/huggingface/transformers/blob/main/src/transformers/models/opt/modeling_opt.py#L566

class OptWeightInfo(ModelDeployWeightInfo):
    
    def _get_hf_weight_info(self):
        layer_weights = [
            # * Attention部分 layer_norm部分
            WeightInfo(W.pre_attn_ln_gamma,[CkptWeightInfo('model.decoder.layers.{i}.self_attn_layer_norm.weight', identity)], identity),
            WeightInfo(W.pre_attn_ln_gamma,[CkptWeightInfo('model.decoder.layers.{i}.self_attn_layer_norm.bias', identity)], identity),

            # *  Attention部分
            WeightInfo(W.attn_qkv_w, [
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.q_proj.weight', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.k_proj.weight', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.v_proj.weight', identity),
                ], functools.partial(merge_qkv_hf)),
            WeightInfo(W.attn_qkv_b,[
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.q_proj.bias', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.k_proj.bias', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.v_proj.bias', identity),
                ], functools.partial(merge_qkv_b)),
            
            WeightInfo(W.attn_o_w,[CkptWeightInfo('model.decoder.layers.{i}.self_attn.out_proj.weight', identity)], transpose),
            WeightInfo(W.attn_o_b,[CkptWeightInfo('model.decoder.layers.{i}.self_attn.out_proj.bias', identity)], identity),

            # * Attention后
            WeightInfo(W.post_ln_gamma,[CkptWeightInfo('model.decoder.layers.{i}.final_layer_norm.weight', identity)], identity),
            WeightInfo(W.post_ln_beta,[CkptWeightInfo('model.decoder.layers.{i}.final_layer_norm.bias', identity)], identity),
            
            # * FFN部分 
            WeightInfo(W.ffn_w3,[CkptWeightInfo('model.decoder.layers.{i}.fc1.weight', identity)], transpose),
            WeightInfo(W.ffn_b3,[CkptWeightInfo('model.decoder.layers.{i}.fc1.bias', identity)], identity),
            WeightInfo(W.ffn_w2,[CkptWeightInfo('model.decoder.layers.{i}.fc2.weight', identity)], transpose),
            WeightInfo(W.ffn_b2,[CkptWeightInfo('model.decoder.layers.{i}.fc2.bias', identity)], identity),
        ]
        
        weights = [
            WeightInfo(W.embedding, [CkptWeightInfo('model.decoder.embed_tokens.weight', identity)], identity),
            WeightInfo(W.positional_embedding,[CkptWeightInfo('model.decoder.embed_positions.weight', identity)], identity),
            WeightInfo(W.final_ln_gamma,[CkptWeightInfo('model.decoder.final_layer_norm.weight', identity)], identity),
            WeightInfo(W.final_ln_beta,[CkptWeightInfo('model.decoder.final_layer_norm.bias', identity)], identity),
            WeightInfo(W.lm_head,[CkptWeightInfo('lm_head.weight', identity)], identity),
        ]
        
        return ModelWeightInfo(layer_weights=layer_weights, weights=weights, tp_strategy=self._get_gpt_style_tp_strategy())


class OPT_125M(GPT):
    @staticmethod
    def get_weight_cls():
        return OptWeightInfo

    @classmethod
    def _create_config(cls, ckpt_path: str):
        config_path = os.path.join(ckpt_path, 'config.json')
        with open(config_path) as f:
            config_json = json.load(f)
        config = GptInitModelParameters(
            head_num=0,
            size_per_head=0, 
            layer_num=0, 
            max_seq_len=0, 
            vocab_size=50272,
        )
        config.head_num=config_json['num_attention_heads']
        config.layer_num=config_json.get('num_hidden_layers', 12)
        config.size_per_head=config_json['hidden_size'] // config_json['num_attention_heads']
        config.vocab_size=config_json['vocab_size']
        config.hidden_size=config_json['hidden_size']
        config.max_seq_len = 2048
        return config

register_model('OPT_125M', OPT_125M, ['facebook/opt-125m'])
```

**Comment by samaritan1998** [comment]
from maga_transformer.utils.util import get_config_from_path
from maga_transformer.config.gpt_init_model_parameters import GptInitModelParameters
from maga_transformer.utils.model_weight import W, WeightInfo, \
    ModelWeightInfo, ModelDeployWeightInfo, CkptWeightInfo, identity, transpose
from maga_transformer.models.gpt import GPT
from maga_transformer.utils.model_weight import (W, WeightInfo, ModelWeightInfo, ModelDeployWeightInfo,
                                                 CkptWeightInfo, identity, zeros, transpose, transpose_pad,
                                                 merge_qkv_b, merge_qkv_hf,concat_0)
from maga_transformer.model_factory_register import register_model
from typing import Any, Dict,List, Tuple, Union
from maga_transformer.utils.group_quant_weight_util import get_layer_group_quant_weight_info
import os 
import json 
import functools
import torch

# * https://github.com/huggingface/transformers/blob/main/src/transformers/models/opt/modeling_opt.py#L566

class OptWeightInfo(ModelDeployWeightInfo):
    
    def _get_weight_info(self):
        layer_weights = [
            # * Attention之前 layer_norm部分
            WeightInfo(W.pre_ln_gamma, [CkptWeightInfo('model.decoder.layers.{i}.self_attn_layer_norm.weight', identity)], identity),
            WeightInfo(W.pre_ln_beta, [CkptWeightInfo('model.decoder.layers.{i}.self_attn_layer_norm.bias', identity)], identity),

            # *  Attention
            WeightInfo(W.attn_qkv_w, [
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.q_proj.weight', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.k_proj.weight', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.v_proj.weight', identity),
                ], functools.partial(merge_qkv_hf)),

            WeightInfo(W.attn_qkv_b,[
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.q_proj.bias', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.k_proj.bias', identity),
                CkptWeightInfo('model.decoder.layers.{i}.self_attn.v_proj.bias', identity),
                ], functools.partial(merge_qkv_b)),
            
            WeightInfo(W.attn_o_w,[CkptWeightInfo('model.decoder.layers.{i}.self_attn.out_proj.weight', identity)], transpose),
            WeightInfo(W.attn_o_b,[CkptWeightInfo('model.decoder.layers.{i}.self_attn.out_proj.bias', identity)], identity),

            # * Attention之后 layer_norm部分 FFN之前
            WeightInfo(W.post_ln_gamma,[CkptWeightInfo('model.decoder.layers.{i}.final_layer_norm.weight', identity)], identity),
            WeightInfo(W.post_ln_beta,[CkptWeightInfo('model.decoder.layers.{i}.final_layer_norm.bias', identity)], identity),
            
            # * FFN部分 
            WeightInfo(W.ffn_w3,[CkptWeightInfo('model.decoder.layers.{i}.fc1.weight', identity)], transpose),
            WeightInfo(W.ffn_b3,[CkptWeightInfo('model.decoder.layers.{i}.fc1.bias', identity)], identity),
            WeightInfo(W.ffn_w2,[CkptWeightInfo('model.decoder.layers.{i}.fc2.weight', identity)], transpose),
            WeightInfo(W.ffn_b2,[CkptWeightInfo('model.decoder.layers.{i}.fc2.bias', identity)], identity),
        ]
        
        weights = [
            WeightInfo(W.embedding, [CkptWeightInfo('model.decoder.embed_tokens.weight', identity)], identity),
            WeightInfo(W.positional_embedding,[CkptWeightInfo('model.decoder.embed_positions.weight', identity)], identity),
            WeightInfo(W.final_ln_gamma,[CkptWeightInfo('model.decoder.final_layer_norm.weight', identity)], identity),
            WeightInfo(W.final_ln_beta,[CkptWeightInfo('model.decoder.final_layer_norm.bias', identity)], identity),
            WeightInfo(W.lm_head,[CkptWeightInfo('lm_head.weight', identity)], identity),
        ]
        
        return ModelWeightInfo(layer_weights=layer_weights, weights=weights, tp_strategy=self._get_gpt_style_tp_strategy())


class OPT_125M(GPT):

    @classmethod
    def get_tokenizer(cls, config:GptInitModelParameters):
        tokenizer_config_file=os.path.join(config.tokenizer_path,"tokenizer_config.json")
        if os.path.exists(tokenizer_config_file):
            return super().get_tokenizer(config)
        else:
            raise Exception("no file about opt tokenizer")

    @staticmethod
    def get_weight_cls():
        return OptWeightInfo

    @classmethod
    def _create_config(cls, ckpt_path: str):
        config_dict = get_config_from_path(ckpt_path)
        # config_path = os.path.join(ckpt_path, 'config.json')
        # with open(config_path) as f:
        #     config_json = json.load(f)
        print("config_dict:", config_dict)
        config = GptInitModelParameters(
            head_num=config_dict['num_attention_heads'],
            size_per_head=config_dict['hidden_size'] // config_dict['num_attention_heads'], 
            layer_num=config_dict.get('num_hidden_layers', 12), 
            vocab_size= config_dict['vocab_size'],
            max_seq_len=config_dict['max_position_embeddings']
            #has_lm_head_bias=True,
            #has_positional_encoding=True,
           # has_pre_decoder_layernorm=False,
           # has_post_decoder_layernorm=True,
           #has_positional_encoding=True,
           #has_post_decoder_layernorm=True,
           #inter_size=config_json["ffn_dim"],
           #tie_word_embeddings = config_json.get('tie_word_embeddings', False)
        )
        config.layernorm_type = 'pre_layernorm'
        #config.layernorm_eps=1e-05
        #config.has_pre_decoder_layernorm=True,
        config.has_post_decoder_layernorm=True
        #config.layernorm_eps = config_json['layernorm_epsilon']
        #config.head_num_kv = config.head_num
        config.hidden_size = config_dict['hidden_size']
        config.inter_size = config_dict["ffn_dim"]
        config.has_positional_encoding = True
        #config.special_tokens.eos_token_id = config_json['eos_token_id']
        #config.layernorm_type = 'pre_layernorm'
        config.activation_type = 'relu'
        #config.head_num = config_json['num_attention_heads']
        #config.layer_num = config_json.get('num_hidden_layers', 12)
        #config.size_per_head = config_json['hidden_size'] // config_json['num_attention_heads']
        #config.vocab_size = config_json['vocab_size']
        #config.hidden_size = config_json['hidden_size']
        #config.max_seq_len = 4096
        config.add_special_tokens = True
        config.special_tokens.eos_token_id = config_dict.get('eos_token_id', 2)
        config.special_tokens.pad_token_id = config_dict.get('pad_token_id', 1)
        config.special_tokens.bos_token_id = config_dict.get('bos_token_id', 2)
        #config.head_num_kv = config.head_num
        #config.tie_word_embeddings = config_json.get('tie_word_embeddings', False)
        #print("config.special_tokens.eos_token_id",config.special_tokens.eos_token_id)
        #print("config.special_tokens.pad_token_id",config.special_tokens.pad_token_id)
        return config

register_model('OPT_125M', OPT_125M, ['facebook/opt-125m'])
